global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: ingestion
    static_configs:
      - targets: ["ingestion:8001"]
  - job_name: orchestrator
    static_configs:
      - targets: ["orchestrator:8002"]
  - job_name: restaurant
    static_configs:
      - targets: ["restaurant:8003"]
  - job_name: courier
    static_configs:
      - targets: ["courier:8004"]
  - job_name: dashboard-api
    static_configs:
      - targets: ["dashboard-api:8005"]
  - job_name: load-gen
    static_configs:
      - targets: ["load-gen:8006"]
